//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyRecipesEntities : DbContext
    {
        private static MyRecipesEntities _context;

        public MyRecipesEntities()
            : base("name=MyRecipesEntities")
        {
        }

        public static MyRecipesEntities GetContext()
        {
            if (_context == null)
                _context = new MyRecipesEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CookingStage> CookingStages { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientOfStage> IngredientOfStages { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
